### ISSUE TITLE
Typescript types of `create` don't match Zustand.

### ISSUE THREAD

**Issue by crubier** [Diablow/zustand-store-addons#2]
The following code (not a special case) does not work with `import create from "zustand-store-addons";` but works with `import create from "zustand";` :

```typescript
import create from "zustand-store-addons";

export type AppStore = {
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
};

export const useLabellingStore = create<AppStore>(
  (set) => ({
    isOpen: false,
    setIsOpen: (isOpen: boolean) => set({ isOpen }),
  })
);
```

I get this error, because `zustand-store-addons` wants the `set` function to be called with something of type `PartialState<AppStore, keyof AppStore>` which reduces to `Pick<AppStore, keyof AppStore>`.

<img width="1213" alt="Screenshot 2021-06-21 at 09 23 58" src="https://user-images.githubusercontent.com/2954572/122731555-54c1ef80-d273-11eb-9967-bf9422d1794e.png">

While `zustand` wants the `set` function to be called with something of type `PartialState<AppStore, "isOpen">` 

<img width="1114" alt="Screenshot 2021-06-21 at 09 30 07" src="https://user-images.githubusercontent.com/2954572/122731520-4e337800-d273-11eb-9ba9-3f7f5637c6ed.png">

**Comment by crubier** [comment]
To clarify: this seems to be a different issue than #1 (albeit related to typescript types)

**Comment by crubier** [comment]
Another point on this:

In terms of typing, doing this solves the problem (Use a function instead of the new partial state as an argument of the call to `set`)
 
```typescript
import create from "zustand-store-addons";

export type AppStore = {
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
};

export const useLabellingStore = create<AppStore>(
  (set) => ({
    isOpen: false,
    setIsOpen: (isOpen: boolean) => set((state) => {...state, isOpen }),
  })
);
```

BUT triggers an actual massive problem: Now each call to `setIsOpen` triggers a render of all my app. This is not the case when using `zustand`. 

So this solution (creating massive runtime problems) is worse than the initial problem (typing problem).

**Comment by crubier** [comment]
So my workaround for now is:



```typescript
import create from "zustand-store-addons";

export type AppStore = {
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
};

export const useLabellingStore = create<AppStore>(
  (set) => ({
    isOpen: false,
    // @ts-ignore See https://github.com/Diablow/zustand-store-addons/issues/2
    setIsOpen: (isOpen: boolean) => set({ isOpen }),
  })
);
```

**Comment by Diablow** [comment]
You're right. This seems to be popping since zustand version 3.3.3
